import os

env = SConscript("godot-cpp/SConstruct")
sources = Glob("src/*.cpp")

env.Tool('compilation_db')
env.Alias('compiledb', env.CompilationDatabase('compile_commands.json'))

conda_prefix = os.environ.get("CONDA_PREFIX")

if conda_prefix:
    base_include_path = os.path.join(conda_prefix, "Library", "include")
    rdkit_include_path = os.path.join(base_include_path, "rdkit")
    lib_path = os.path.join(conda_prefix, "Library", "lib")

    env.Append(CPPPATH=[base_include_path, rdkit_include_path])
    env.Append(LIBPATH=[lib_path])
    env.Append(LIBS=["RDKitGraphMol", "RDKitFileParsers"])
else:
    print("Error: CONDA_PREFIX environment variable not found. Is your environment activated?")

target_path = "../bin/molecule_importer" + env["suffix"] + env["SHLIBSUFFIX"]
lib = env.SharedLibrary(target=target_path, source=sources)
Default(lib)
